name: Publish extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install dependencies
        run: cd extension && npm install

      - name: Publish to Visual Studio Marketplace
        run: cd extension && npm run publish
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}